name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update project version in pom files
        run: |
          #branch_name=release-${RELEASE_VERSION}-change
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com
          #git checkout -b ${branch_name}

          mvn -B versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false

          #find . -name 'pom.xml' | xargs git add
          #git status
          #git commit -m"Release ${RELEASE_VERSION}"

          #origin_url=https://x-access-token:${GITHUB_TOKEN}@github.com/bugInspector/javainspector.git
          #git remote set-url origin ${origin_url}
          #git push origin ${branch_name} --force-with-lease
          #git fetch origin --prune
          #lst_commit=$(git rev-parse origin/main)
          #release_commit=$(git rev-parse origin/${branch_name})
          #git request-pull $lst_commit origin $release_commit

        env:
          GITHUB_USERNAME: ${{ github.actor }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a PR into repository
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Release ${{ github.event.release.tag_name }}
          base: main
          branch: release-${{ github.event.release.tag_name }}-change

      - name: Publish package
        run: |
          pwd
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#name: Publish package to the Maven Central Repository and GitHub Packages
#on:
#  release:
#    types: [created]
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#      - name: Publish to the Maven Central Repository
#        run: mvn --batch-mode deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#      - name: Set up Java for publishing to GitHub Packages
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#      - name: Publish to GitHub Packages
#        run: mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}