name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Maven
        run: |
          pwd
          ls -la
          mvn -B package --file pom.xml

      - name: Update project version in pom files
        run: |
          pwd
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com

          mvn -B versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false

        env:
          GITHUB_USERNAME: ${{ github.actor }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: |
          pwd
          ls -la
          mvn -B package --file pom.xml

      - name: Publish package
        run: |
          pwd
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#name: Publish package to the Maven Central Repository and GitHub Packages
#on:
#  release:
#    types: [created]
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#      - name: Publish to the Maven Central Repository
#        run: mvn --batch-mode deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#      - name: Set up Java for publishing to GitHub Packages
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#      - name: Publish to GitHub Packages
#        run: mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}