name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Maven
        run: |
          pwd
          ls -la
          mvn -B package --file pom.xml

      - name: Check release correctness
        run: |
          pwd
          project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [ $project_version != $RELEASE_VERSION ]; then
            echo "Project version and Release version are not equal, please create tag using workflow specified for this"
            exit 1
          fi

          git fetch origin
          commit_id=$(git rev-parse HEAD)
          echo "commit id we are going to check $commit_id"
          contain_commit=$(git branch -r --contains $commit_id)
          echo "remote branches which contain $commit_id: $contain_commit"
          if [[ ! ${contain_commit} =~ "origin/main" ]]; then
            echo "Main branch does not contain release commit"
            exit 1
          fi

        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}

      - name: Build with Maven
        run: |
          pwd
          ls -la
          mvn -B package --file pom.xml

      - name: Publish package
        run: |
          pwd
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#name: Publish package to the Maven Central Repository and GitHub Packages
#on:
#  release:
#    types: [created]
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#      - name: Publish to the Maven Central Repository
#        run: mvn --batch-mode deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#      - name: Set up Java for publishing to GitHub Packages
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#      - name: Publish to GitHub Packages
#        run: mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}