name: Release Cycle
on:
  release:
    types: [created]
jobs:
  demoTests:
    uses: ./.github/workflows/demo.yml
  demoTests1:
    needs: [ demoTests ]
    uses: ./.github/workflows/demo1.yml
  checkRelease:
    needs: [ demoTests, demoTests1 ]
    uses: ./.github/workflows/check_release.yml
  release:
    needs: [ demoTests, demoTests1, checkRelease ]
    uses: ./.github/workflows/release.yml