name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish package
        run: |
          pwd
          mvn --batch-mode deploy
          #mvn --batch-mode deploy --file pom.xml
          #cd core
          #pwd
          #mvn --batch-mode deploy
          #cd car
          #pwd
          #mvn --barch-mode deploy
          #mvn --batch-mode -X -e deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#name: Publish package to the Maven Central Repository and GitHub Packages
#on:
#  release:
#    types: [created]
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#      - name: Publish to the Maven Central Repository
#        run: mvn --batch-mode deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#      - name: Set up Java for publishing to GitHub Packages
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#      - name: Publish to GitHub Packages
#        run: mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}